### PR TITLE
Fix to convert decimal to String and bigint to BigInt

### LINKED ISSUE #42: Handling of `bigint` and `decimal` types
## Summary

deno_mysql currently treats MySQL's `bigint` and `decimal` as the JavaScript's `Number`.

However, these types cannot be accurately represented by the `Number`.

The following code reproduces this problem:

**mod.ts:**

```typescript
import { Client } from "https://deno.land/x/mysql@1.9.1/mod.ts";

const client = await new Client().connect({
  hostname: "localhost",
  port: 3306,
  username: "test",
  db: "test",
  password: "test",
});

await client.query(`DROP TABLE IF EXISTS test`);
await client.query(`CREATE TABLE test (
  id int(11) NOT NULL AUTO_INCREMENT,
  bigint_column bigint NOT NULL,
  decimal_column decimal(65,30) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=MEMORY DEFAULT CHARSET=utf8mb4`);

const bigint = "9223372036854775807";
const decimal = "0.012345678901234567890123456789";
await client.execute(`
  INSERT INTO test (bigint_column, decimal_column)
  VALUES (${bigint}, ${decimal})`);

console.log(await client.query(`SELECT * FROM test`));
```

```shell
$ deno run --allow-net ./mod.ts
INFO connecting localhost:3306
INFO connected to localhost
[
 { id: 1, bigint_column: 9223372036854776000, decimal_column: 0.012345678901234568 }
]
```

- deno@v0.42.0
- deno_mysql@v1.9.1

## Possible solutions

- Always treat `bigint` and `decimal` as `String` (probably the simplest solution).
- Provide options that change the handling of these types (like [node-mysql](https://github.com/mysqljs/mysql)).
  - node-mysql provides `supportBigNumbers` and `bigNumberStrings` options.

These are just ideas, so any feedback would be appreciated :smile:

## Ref

- https://dev.mysql.com/doc/refman/5.7/en/numeric-type-syntax.html
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number

### PR DESCRIPTION
**Pull request by uki00a**
This PR tries to resolve #42.

- Fixed to convert MySQL's decimal type to `String`.
- Fixed to convert MySQL's bigint type to `BigInt`.

@manyuanrong @magichim Please review🙏

### CODE REVIEW

**Comment by magichim** [comment]
@uki00a BigInt is LGTM. but long decimal type(0.1232131313123123123231231) should be used as string? "0.0123123123123123"

**Comment by uki00a** [comment]
@magichim I'm sorry for my ignorance, but what do you mean by "long decimal type"? Is that type different from "MYSQL_TYPE_DECIMAL"?

**Comment by magichim** [comment]
@uki00a Yes your word is right. My expression is wrong. anyway, decimal type should be string in js? I also could not find that maintain origianal decimal value. because js engine automatically change some value at part of end.

**Comment by uki00a** [comment]
@magichim 
> but long decimal type(0.1232131313123123123231231) should be used as string? "0.0123123123123123"

I suspect that in some applications, the loss of accuracy is unacceptable (`0.1232131313123123123231231` => `"0.0123123123123123"`).

To avoid that, I think that MySQL's decimal type should be treated as a js string.

**Comment by uki00a** [comment]
@magichim Thanks for the review!

**Comment by uki00a** [comment]
Oops, CI fails. I'll look into it.

File: src/packets/parsers/result.ts [hunk 1]
```diff
@@ -97,9 +98,10 @@ function convertType(field: FieldInfo, val: string): any {
     case MYSQL_TYPE_TINY:
     case MYSQL_TYPE_SHORT:
     case MYSQL_TYPE_LONG:
-    case MYSQL_TYPE_LONGLONG:
     case MYSQL_TYPE_INT24:
       return parseInt(val);
```
Comment (uki00a) [inline src/packets/parsers/result.ts:102]: @magichim

This PR introduces the failure of the [`testPool`](https://github.com/manyuanrong/deno_mysql/blob/b18da6cdfb692e3f9fc36e9d0efe3302020b3f3b/test.ts#L130-L145).

The cause is that `select 1` returns a js `BigInt` instead of `Number`.

What do you think of the following modifications to fix this problem?

```suggestion
      if (val > Number.MAX_SAFE_INTEGER) {
        return BigInt(val);
      } else {
        return parseInt(val);
      }
```

Comment (magichim) [reply src/packets/parsers/result.ts:102]: I think It's good case.

Comment (magichim) [reply src/packets/parsers/result.ts:102]: @uki00a  The is another question, your test.ts file is working exactly? My deno version is 1.0 but Deno.test's fn function is not working. In terminal, type "deno run -A test.ts." just work createTestDB function case. How about you?

Comment (uki00a) [reply src/packets/parsers/result.ts:102]: @magichim 
> The is another question, your test.ts file is working exactly?
> In terminal, type "deno run -A test.ts." just work createTestDB function case. How about you?

Yes. In my local environment(deno 1.0.0), all tests pass now.

You need to run `deno test -A` instead of `deno run -A test.ts`.

Comment (uki00a) [reply src/packets/parsers/result.ts:102]: @magichim 
I've fixed the problem at #47.
Please review it again🙏

Comment (magichim) [reply src/packets/parsers/result.ts:102]: @uki00a 
Oh! really thank you. Deno command is changed haha...
Anyway above your code is MYSQL_TYPE_LONGLONG case?

Comment (uki00a) [reply src/packets/parsers/result.ts:102]: @magichim 

> Anyway above your code is MYSQL_TYPE_LONGLONG case?

No. That's the MYSQL_TYPE_LONGLONG case.

> How about removing decimal test code? It's unsafety.

That problem has been fixed at #47.

Comment (magichim) [reply src/packets/parsers/result.ts:102]: @uki00a 

Looks good~!!

OKay! Try to merge again! Thanks!
